#!/bin/bash

set -eu
#Profiling
#PS4='+ $(date "+%s.%N")\011 '
#set -x


. /usr/lib/shlib/logs3.sh
. /usr/lib/shlib/utils.sh

set +eu
# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
set -eu

cleanup() {
  err=$?
  if [ $err != 0 ]; then
    log notice "$0 terminating on error $err"
  else
    log notice "$0 terminating"
  fi
}

trap cleanup 0

xrdb -merge ~/.Xresources
setxkbmap -layout "us,fi"

export SUDO_ASKPASS=/usr/bin/xaskpass
export SSH_ASKPASS=/usr/bin/xaskpass

nj tmux -L "awesome_${DISPLAY}" new-session -s awe -d || true
tmux -L "awesome_${DISPLAY}" new-session -s keepalive -d || true
# need awesome in session in order to let systemd kill all its children so x dies
# wihout sigterm
#systemctl --user start "tmux@${DISPLAY}.service"

[ -f ~/.xinitrc.local ] && . ~/.xinitrc.local
# No restart handling but these need to be in systemd session and processes
# started by systemd --user are not.
# Also it should be that session services are in hidepid group
nj xss-lock -n /usr/lib/xsecurelock/dimmer -l -- /usr/bin/sh mylock &
awesome --no-argb

# for subshells too
#trap '' TERM INT HUP
#wait
