case "$(tty)" in
  # Logout terminal after 600 seconds
  /dev/tty[0-9]*)
    TMOUT=600
    #[[ $- = *l* ]] && return
    alias startx='exec myx'
    alias myway='exec sh myway'

    ;;
esac

if [ -n "${SSH_CONNECTION:-}" ]; then
  if [ -x /usr/lib/ssh/x11-ssh-askpass ]; then
    export SUDO_ASKPASS=/usr/lib/ssh/x11-ssh-askpass
    export SSH_ASKPASS=/usr/lib/ssh/x11-ssh-askpass
  fi
fi

if [[ $TERM == *-256color || $TERM == *-kitty ]] && [[ -z $TMUX ]] && [[ -z $SCREEN ]]; then
  eval $(dircolors -b)

  echo "Setting solarized dark base16 256colors"
  source $HOME/.zsh/data/base16-shell/scripts/base16-solarized-dark.sh
fi


source $HOME/.zsh/options.zsh


# Load a few modules {{{{
for mod in parameter complist deltochar mathfunc ; do
    zmodload -i zsh/${mod} 2>/dev/null || print "Notice: no ${mod} available :("
done && builtin unset -v mod

# autoload zsh modules when they are referenced
zmodload -a  zsh/stat    zstat
zmodload -a  zsh/zpty    zpty
zmodload -ap zsh/mapfile mapfile


autoload -Uz zmv
autoload -Uz zed

# NOTE: must come before zsh-history-substring-search & zsh-syntax-highlighting.
autoload -Uz select-word-style
# do this afte zsh-syntax higihlight if you do not want to override default widgets...
select-word-style shell

source $HOME/.zsh/data/zsh-autosuggestions/zsh-autosuggestions.zsh
if [ "$TERM" != linux ]; then
  :
  #ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=59'
else
  ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=1'
  #ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=5'
  #ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=4'
fi
# TODO some bindkeys ignored because we call bindkey -e later

#source $HOME/.zsh/zsh-history-substring-search/zsh-history-substring-search.zsh
#HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
source $HOME/.zsh/data/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# }}}}

source $HOME/.zsh/completion.zsh
source $HOME/.zsh/prompt.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/bindings.zsh
source $HOME/.zsh/commands.zsh



# Local and host-specific overrides.
[ ! -f $HOME/.zshrc-local.zsh ] || . $HOME/.zshrc-local.zsh

#Sources
#http://chneukirchen.org/blog/

# vim:set ts=8 sw=2 fdm=marker foldmarker={{{{,}}}}:
